name: Run terraform demo

on:
  workflow_dispatch:
    inputs:
      repo-name: 
        description: "Name of the repository"
        required: true
      repo-description:
        description: "Description of repository"
        required: true

env:
  TF_VAR_gh_token: ${{ secrets.CUSTOM_TOKEN }}
  TF_VAR_app_name: ${{ github.event.inputs.repo-name }}
  TF_VAR_app_description: ${{ github.event.inputs.repo-description }}

defaults:
  run:
    working-directory: git-init

jobs:
  Terraform_script:
    runs-on: ubuntu-latest
    name: Run Terraform

    steps:
      - name: checkout files
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform init
        id: init
        run: terraform init
      
      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
      
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
